create table pessoa(
	CPF(CHAR(11),
    NOME VARCHAR(100),
    PRIMARY KEY(CPF)
);

CREATE TABLE CNH(
		NUM INTEGER PRIMARY KEY,
        CPF CHAR(11),
        foreign key(CPF) REFERENCES PESSOA (CPF),
       UNIQUE(CPF) -- FAZ COM Q FIQUE 1 PRA 1 O RELACIONAMENTO POIS NAO DEIXA REPETIR
);

CREATE TABLE FUNCIONARIOS(
		CPF CHAR(30),
        NOME CHAR(30),
        VAGA INTEGER,
        primary key(CPF)
);

CREATE TABLE DEPARTAMENTOS(
		ID CHAR(30),
        NOME CHAR(30),
        ORCAMENTO INTEGER,
        primary key(ID)
);

CREATE TABLE LOCALIDADES(
		ENDERECO CHAR(30),
        CAPACIDADE CHAR(30),
        primary key(ENDERECO)
);

CREATE TABLE TRABALHA_EM2(cpf
	CHAR (11),
	id-depto INTEGER,
	endereco CHAR(20),
    desde DATE,
	PRIMARY KEY (cpf, id-depto, endereco),
FOREIGN
KEY
(cpf)
REFERENCES
FUNCIONARIOS(cpf),
FOREIGN
KEY
(endereco)
REFERENCES
LOCALIDADES(endereco),
FOREIGN
KEY
(id-depto)
REFERENCES
DEPARTAMENTOS(id-depto))

CREATE TABLE REPORTA_A (
			(SUPERVISOR_CPF CHAR(11),
            SUBORDINADO_CPF CHAR(11),
            PRIMARY KEY (supervisor_cpf, subordinado_cpf),
FOREIGN KEY (supervisor_cpf) REFERENCES FUNCIONARIOS(cpf),
FOREIGN KEY (subordinado_cpf) REFERENCES FUNCIONARIOS(cpf)
);

CREATE table DEPARTAMENTOS_GERENCIA(
	ID_DEP CHAR (20),
    NOME_DEP CHAR (20),
    CPF CHAR (11) NOT NULL,
    DESDE DATE,
    PRIMARY KEY (ID_DEP),
    FOREIGN KEY (CPF) REFERENCES FUNCIONARIOS(CPF) ON DELETE NO ACTION
);
    
CREATE table TRABALHA_EM(
	ID_DEP CHAR(20),
    NOME_DEP CHAR (20),
    CPF CHAR (11) NOT NULL,
    DESDE DATE,
    PRIMARY KEY (ID_DEP, NOME_DEP, CPF),
    FOREIGN KEY (ID_DEP) REFERENCES departamentos(ID_DEP),
    FOREIGN KEY (CPF) REFERENCES FUNCIONARIOS(CPF),
	FOREIGN KEY (CPF) REFERENCES FUNCIONARIOS(CPF)
);	

CREATE TABLE APOLICE_DEP(
		NOME CHAR (20),
        IDADE INTEGER,
        custo REAL,
cpf CHAR (11),
PRIMARY KEY (nome, cpf),
FOREIGN KEY (cpf) REFERENCES FUNCIONARIOS(cpf) ON DELETE cascade
);

CREATE TABLE FUNCIONARIOS(
		CPF CHAR(30),
        NOME CHAR(30),
        VAGA INTEGER,
        primary key(CPF)
);

CREATE TABLE FUNC_HORISTA(
		CPF CHAR(30),
        SALARIO_HORA DECIMAL,
        HORAS_TRABALHADAS INTEGER,
        primary key(CPF),
        foreign key(CPF) REFERENCES FUNCIONARIOS(CPF) ON DELETE CASCADE
        ON update CASCADE
);

CREATE TABLE FUNC_CONTRATADO(
		CPF CHAR(30),
        ID INTEGER,     
        primary key(CPF)
);


    
    
    
    
    
    