contigua:
	
	# Compilando a implementacao da fila
	gcc -c fila_contigua.c
	
	# Compilando e gerando o executavel
	gcc main.c fila_contigua.o -o main

	# Executando
	./main_filaContigua

encadeada:
	# Compilando a implementacao da fila
	gcc -c fila_encadeada.c
	
	# Compilando e gerando o executavel
	gcc main.c fila_encadeada.o -o main
	
	# Executando
	./main

clean:
	rm *.o	
	rm main
	