-- create database chope;
-- use chope;
DROP TABLE IF EXISTS CLIENTE, PEDIDO, ENDERECO, FORNECEDOR;

create table CLIENTE(
	ID_CLI INTEGER primary KEY,
    NOME VARCHAR (30),
    SOBRENOME VARCHAR (50)
);    
CREATE TABLE PEDIDO(
	ID INTEGER PRIMARY KEY,
    QUANTIDADE INTEGER,
    DATA_PED DATE,
    PAGAMENTO VARCHAR (30)
);
CREATE TABLE ENDERECO(
	ID INTEGER PRIMARY KEY,
    BAIRRO VARCHAR (30),
    RUA VARCHAR (30),
    NRO INTEGER
);
CREATE TABLE FORNECEDOR(
	CNPJ INTEGER PRIMARY KEY,
    NOME varchar (40),
    TELEFONE INTEGER
);    
CREATE TABLE PRODUTO(
	ID INTEGER PRIMARY KEY,
    STATS VARCHAR (30),
    
    
