-- https://github.com/Osmarborges/2022-01/tree/main/BancodeDados1/Trabalho%20Modelo%20Entidade-Relacionamento/entrega2
-- create database chope;
 use chope;
DROP TABLE IF EXISTS
 CLIENTE, CLIENTE_FISICO, CLIENTE_JURIDICO, CLIENTE_TEM_TELEFONE, ENDERECO, FORNECEDOR, FORNECEDOR_TEM_TELEFONE, CHOPP,
 PRODUTO, PRODUTO_MAQUINA, PRODUTO_CILINDRO, PRODUTO_BARRIL, FORNECEDOR_FORNECE_PRODUTO, 
 FUNCIONARIO, FUNC_ENTREGADOR, FUNC_VENDAS, FUNCIONARIO_TEM_TELEFONE, PEDIDO, PEDIDO_TEM_PRODUTO;
create table CLIENTE(
	ID_CLI INTEGER primary KEY,
    NOME VARCHAR (30),
    SOBRENOME VARCHAR (50)
); 
create table CLIENTE_FISICO(
	ID_CLI INTEGER primary KEY,
    CPF INTEGER,
    RG INTEGER,
    foreign key (ID_CLI) REFERENCES CLIENTE (ID_CLI)
);
create table CLIENTE_JURIDICO(
	ID_CLI INTEGER primary KEY,
    RAZAO_SOCIAL VARCHAR (50),
    EMAIL VARCHAR(50),
    foreign key (ID_CLI) REFERENCES CLIENTE (ID_CLI)
);
CREATE TABLE CLIENTE_TEM_TELEFONE(
	COD_PAIS INTEGER,
    DDD INTEGER,
    NRO INTEGER,
    ID_CLI INTEGER,
    PRIMARY KEY (NRO, ID_CLI),
    FOREIGN KEY (ID_CLI) REFERENCES CLIENTE(ID_CLI)    
);
CREATE TABLE ENDERECO(
	ID INTEGER,
    BAIRRO VARCHAR (30),
    RUA VARCHAR (30),
    NRO INTEGER,
    CIDADE VARCHAR(60),
    ESTADO VARCHAR(60),
    ID_CLI INTEGER,    
    PRIMARY KEY (ID, ID_CLI),
    FOREIGN KEY (ID_CLI) REFERENCES CLIENTE(ID_CLI)
);
CREATE TABLE FORNECEDOR(
	CNPJ INTEGER PRIMARY KEY,
    NOME varchar (40),
    email varchar (40)
); 
CREATE TABLE FORNECEDOR_TEM_TELEFONE(
	COD_PAIS INTEGER,
    DDD INTEGER,
    NRO INTEGER,
    ID_CLI INTEGER,
    PRIMARY KEY (NRO, ID_CLI),
    FOREIGN KEY (ID_CLI) REFERENCES CLIENTE(ID_CLI)    
);   
CREATE TABLE CHOPP(
	TIPO_DESCRICAO VARCHAR(60) PRIMARY KEY,
    VALOR_LITRO FLOAT,    
    VALIDADE DATE    
);
CREATE TABLE PRODUTO(
	ID_PROD INTEGER PRIMARY KEY,
    STATS VARCHAR (30),
    MARCA VARCHAR (40),
    PRECO FLOAT 
);
CREATE TABLE PRODUTO_MAQUINA(
	VOLTAGEM INTEGER,
    VAZAO_HORA INTEGER,
    NRO_TORNEIRAS INTEGER,
    ID_PROD INTEGER,
    FOREIGN KEY (ID_PROD) REFERENCES PRODUTO (ID_PROD)
); 
CREATE TABLE PRODUTO_CILINDRO(
	COR VARCHAR (25),
    PESO FLOAT,
    PRESSAO_MAX INTEGER,
    ID_PROD INTEGER,
    FOREIGN KEY (ID_PROD) REFERENCES PRODUTO (ID_PROD)
); 
CREATE TABLE PRODUTO_BARRIL(
	DIMENSOES VARCHAR (40),
    CAPACIDADE INTEGER,
    PRESSAO_MAX INTEGER,
    ID_PROD INTEGER,
    TIPO_DESCRICAO VARCHAR (50),
    FOREIGN KEY (ID_PROD) REFERENCES PRODUTO (ID_PROD),
    FOREIGN KEY (TIPO_DESCRICAO) REFERENCES CHOPP (TIPO_DESCRICAO)    
);
CREATE TABLE FORNECEDOR_FORNECE_PRODUTO(
	CNPJ INTEGER,
    ID_PROD INTEGER,
    primary key (CNPJ, ID_PROD),
    foreign key (CNPJ) REFERENCES FORNECEDOR(CNPJ),
    FOREIGN KEY (ID_PROD) REFERENCES PRODUTO (ID_PROD)
);
CREATE TABLE FUNCIONARIO(
	CRACHA INTEGER PRIMARY KEY,
    DATA_INICIO DATE,
    DATA_NASC DATE
);        
CREATE TABLE FUNC_ENTREGADOR(
	CAT_HABILITACAO VARCHAR (10),
    NRO_HABILITACAO INTEGER,
    STATS VARCHAR (40),
    CRACHA INTEGER PRIMARY KEY,
    foreign key (CRACHA) REFERENCES FUNCIONARIO (CRACHA)
);   
CREATE TABLE FUNC_VENDAS(
	COMISSAO_PORCENT FLOAT, 
    SALARIO FLOAT,
    EMAIL VARCHAR (40),
    CRACHA INTEGER PRIMARY KEY,
    foreign key (CRACHA) REFERENCES FUNCIONARIO (CRACHA)
);
CREATE TABLE FUNCIONARIO_TEM_TELEFONE(
	COD_PAIS INTEGER,
    DDD INTEGER,
    NRO INTEGER,
    CRACHA INTEGER,
    PRIMARY KEY (NRO, CRACHA),
    FOREIGN KEY (CRACHA) REFERENCES FUNCIONARIO(CRACHA)    
); 
CREATE TABLE PEDIDO(
	ID_PED INTEGER PRIMARY KEY,
    QUANTIDADE INTEGER,
    DATA_PED DATE,
    PAGAMENTO VARCHAR (30),
    CRACHA INTEGER,
    ID_CLI INTEGER,
    FOREIGN KEY (CRACHA) REFERENCES FUNCIONARIO (CRACHA),
	FOREIGN KEY (ID_CLI) REFERENCES CLIENTE (ID_CLI)
);
CREATE TABLE PEDIDO_TEM_PRODUTO(
	ID_PROD INTEGER,
    ID_PED INTEGER,
    PRIMARY KEY (ID_PROD, ID_PED),
    FOREIGN KEY (ID_PROD) REFERENCES PRODUTO (ID_PROD),
    FOREIGN KEY (ID_PED) REFERENCES PEDIDO (ID_PED)
);